#Based on assessment starter for CM6213 individual project
#https://docs.gitlab.com/ee/ci/junit_test_reports.html 11/11/2018
#https://flywaydb.org/getstarted/firststeps/gradle accessed on 13/11/2018
#https://docs.gitlab.com/ee/ci/services/mysql.html accessed 13/11/2018

image: openjdk:10-jdk
services:
  - mysql:latest

variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: password

stages:
- build

before_script:
        - apt update
        - apt install -y mysql-client
        - echo $GRADLE_HOME
        - echo `pwd`
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - rm -f  .gradle/caches/modules-2/modules-2.lock
        - rm -fr .gradle/caches/*/plugin-resolution/
        - chmod +x gradlew
cache:
    paths:
        - .gradle/caches

build:gradle:
    stage: build
    script:
        - ./gradlew build -Pprofiles=ci
        - touch schema.sql
        - mysqldump --no-data $MYSQL_DATABASE -u root -p$MYSQL_ROOT_PASSWORD -h mysql > schema.sql
        - cat schema.sql
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - ./build/libs/*.jar
            - schema.sql
        reports:
            junit: build/test-results/test/TEST-*.xml
        expire_in: 1 week

